//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISTools.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public string mmsi { get; set; }
        public string vsnm { get; set; }
        public Nullable<int> type { get; set; }
        public string @class { get; set; }
    }
}
