//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISTools.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipJourney
    {
        public string mmsi { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lng { get; set; }
        public string sog { get; set; }
        public string cog { get; set; }
        public string time { get; set; }
    }
}
